### ISSUE TITLE
? no Funktion..

### ISSUE THREAD

**Issue by BoraSchninsky** [DMailMan/MMM-MQTTfloorplan#1]
i have added to my config.js but my mirror starts not .. hangs with black screen.
and the installation displays ..

pi@raspberrypi:~/MagicMirror/modules/MMM-MQTTfloorplan $ npm install
npm WARN Invalid version: "1.0"
npm WARN MMM-MQTTfloorplan No description
npm WARN MMM-MQTTfloorplan No repository field.
npm WARN MMM-MQTTfloorplan No README data
npm WARN MMM-MQTTfloorplan No license field.

up to date in 2.27s
found 0 vulnerabilities

can you fix it?

... can you give us a example file for use with IOBROKER !!!!

thanks!!!
greetings from Germany

**Comment by DMailMan** [comment]
Turns out that semver requires three parts to the version number, not two.
Updated package.json and resolved issue.
