### ISSUE TITLE
too much information in string characters....any ideas ?

### ISSUE THREAD

**Issue by Rodriguezjp** [DMailMan/MMM-MQTTfloorplan#4]
Congratulations on the module, it gives a very personal touch to the mirror !!!
but I need your help please.

Hello, I am configuring a module for my Magic-Mirror, but I cannot get the temperature value without the entire character string of the Sonoff-Tasmota with a DHT11 temperature and humidity sensor.
I leave you an image of my problem, in case you can help me. Thanks
Img.frage1.png

![frage1](https://user-images.githubusercontent.com/75023486/103987722-39fc3280-518d-11eb-8c0b-7147ce0b574d.png)

Img.frage2.png
20:31:16 MQT: tele/espejo1/SENSOR = {"Time":"2021-01-07T20:31:16","DHT11":{"Temperature":19.3,"Humidity":26.0,"DewPoint":-0.7},"TempUnit":"C"}

I need to get the Temperature value only, but I don't know how. And I've tried everything. 
I have the module configured with MQTT (Homeassistant)

Ex Module:
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//MMM-MQTTfloorplan - CON IMAGEN 3D de planta de casa !!BUENO
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		{
		module: 'MMM-MQTTfloorplan',
		position: 'bottom_left', 
		config: {
			mqttServer: {
				url: "IP-RASPBERY",
				user: "mqtt", 
				password: "************", 
			},
			floorplan: {
				image: "floorplan-default.png", 
				width: 350, 
				height: 295, 
			},
			subscriptions: [
			{
				topic: 'stat/espejo1/RESULT', // MQTT Topic name !
				label: 'Luz de pruebas1 - Espejo1',	// BULB OK!!
				type: 'light',
				display: { left: 120, top: 60 },
			{
				topic: 'tele/espejo1/SENSOR', 	//Work but everything  I need Only Temperature value !!!!
				label: 'Espejo1 Temp',
				type: 'label',
				display: { left: 350, top: 10}, 
			
},	
]
}
},

Thank you very much for those who can help me get the temperature value, within topic:

example -> topic: ‘tele/espejo1/SENSOR’, bla…bla…bla … Help !!! ???

Happy New Year 2021 to all 😉

**Comment by bertdeelman** [comment]
Hi,

The MQTT output from the Tasmota is JSON instead of a single value. Like true/false or 19.3. There is a function called jsonpointer included in this module. 

So you can use these lines at your config.js. 

           {
                topic: 'tele/espejo1/SENSOR', // MQTT Topic name
                label: 'Temperature',    // Not displayed anywhere, but handy for you to know what you're doing !
                type: 'label',
                jsonpointer: '/DHT11/Temperature',
                display: { left: 265, top: 90, prefix: "", suffix: "°C", decimals: 1 },
            },
            {
                topic: 'tele/espejo1/SENSOR', // MQTT Topic name
                label: 'Humidity',    // Not displayed anywhere, but handy for you to know what you're doing !
                type: 'label',
                jsonpointer: '/DHT11/Humidity',
                display: { left: 265, top: 130, prefix: "", suffix: "%H", decimals: 0},
            }

You should also do one modification at the MMM-MQTTfloorplan.js file. At line 125 you must delete 				toUpperCase(). You cannot uppercase a numeric value. 

Good luck! 

Regards,
Bert

**Comment by Rodriguezjp** [comment]
I'm going to try it and I'll tell you if it works, with your instructions ... thank you very much.
when I try it I will comment again :)

**Comment by Rodriguezjp** [comment]
Hi bertdeelman...you mean this, is it enough ?? I can't get it to work !! now it does not give any value

in config.js

{
            topic: 'tele/espejo1/SENSOR', // MQTT Topic name
            label: 'Temperature',    // Not displayed anywhere, but handy for you to know what you're doing !
            type: 'label',
            jsonpointer: '/DHT11/Temperature',
            display: { left: 265, top: 90, prefix: "", suffix: "°C", decimals: 1 },
        },



in MMM-MQTTfloorplan.js
.
.
123              this.updateDivForItem(
124                               i,
125                          //  value.toUpperCase(),
126                               config);
.
.

![frage3](https://user-images.githubusercontent.com/75023486/104022371-7b5a0580-51c0-11eb-932f-ddde74d6b97f.png)

**Comment by bertdeelman** [comment]
Hi,

Your config.js seems to be ok. 

At the MMM-MQTTfloorplan.js file you should only delete .toUpperCase() so only **value** instead of **value.toUpperCase()**


```
this.updateDivForItem(	
	i, 
	value,
	config);
```

Regards,
Bert

**Comment by Rodriguezjp** [comment]
LOL !!!!!!!! ITS WORKING !!!!!!! THANKS !!!!!! my friend !!!!!!!
![frague 4](https://user-images.githubusercontent.com/75023486/104028645-430af500-51c9-11eb-815b-60c65bd2eda4.png)

**Comment by Rodriguezjp** [comment]
END !!
