### ISSUE TITLE
adjust temperature values

### ISSUE THREAD

**Issue by Rodriguezjp** [DMailMan/MMM-MQTTfloorplan#6]
Is there a way to adjust the temperature values that the mqtt gives you in the module?

I have installed a DHT11 sensor in a sonoff with Tasmota.
the sensor shows me **+1.5 degrees difference** from the actual temperature.

Could you adjust those values from the module?

currently the my .config is like this:

	        	{	
				topic: 'tele/luz_cocina/SENSOR', // Temperatura Espejo !!!! como Muestra
				label: 'Temperatura WC',
				type: 'label',
				jsonpointer: '/DHT11/Temperature',
				display: { left: 100, top: 25, prefix: "", suffix: "°C", decimals: 1}, 					
			},

Thank you very much for this super module. :)

**Comment by bertdeelman** [comment]
Hi,

This MM-module is just to show (MQTT) values and not to adjust them. Have a look at this: [https://tasmota.github.io/docs/DHT11/](url) and [https://tasmota.github.io/docs/Commands/#tempoffset](url) you can  calibrate this sensor. 

Regards,
Bert

**Comment by Rodriguezjp** [comment]
Lol.....you are a great among the greats

works perfectly by entering the values in the tasmota console:

TempOffset 1.5 

![image](https://user-images.githubusercontent.com/75023486/106804016-27c6c480-6665-11eb-9745-231dce3b4e50.png)

thanks for your help again. ;)
